### ISSUE TITLE
0.0.1

### ISSUE THREAD

**Issue by ayazhafiz** [yslide/slide#103]
At some point, I think it would be nice for us to drop a beta release of the slide binary. This will give us a better direction for the things we want to support ahead of that release, what tasks we can postpone, and serve as a large morale-booster/milestone for our work.

I think we need to close the following issues before the first beta release:

- [x] #92 flatten add/sub expressions
- [x] #71 with GCD HEU (this is probably enough for simple polynomials)
- [x] #102/#56 Error handling
- [x] #104 Testing Framework
- [x] #105 Contribution Docs
- [x] #106 flatten mul/div expressions

Obviously we can modify this list depending on feedback. WDYT @luke-bhan @timothycobrien?

**Comment by ayazhafiz** [comment]
Actually I think we can move the error stuff back to 0.2 or further. Instead of that we should set up a test corpus and a nice way of adding arbitrary math tests to see what is failing (there will be a lot of stuff failing).

**Comment by luke-bhan** [comment]
Added some new issues and edited you list to include them. I think #106 is optional as well. I also don't think the error stuff should be moved back. I'd rather make sure we have a solid foundation on how to handle these things before 0.1 especially since theres no rush in publishing, but up to you guys. @ayazhafiz @timothycobrien

**Comment by ayazhafiz** [comment]
Okay sounds good. We'll include the error stuff, I'll add a milestone and start working tonight.

**Comment by ayazhafiz** [comment]
Promoting #106 to 0.1
